name: Cost Janitor

on:
  push:
    branches:
      - main

jobs:
  run-janitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install boto3

      # ✅ Start LocalStack manually
      - name: Start LocalStack
        run: |
          docker run -d -p 4566:4566 \
          -e SERVICES=s3,ec2 \
          -e AWS_DEFAULT_REGION=us-east-1 \
          localstack/localstack

      # ✅ Wait properly (important)
      - name: Wait for LocalStack
        run: sleep 40

      - name: Run Janitor Script (dry run)
        run: python janitor/janitor.py

      - name: Run delete mode
        run: python janitor/janitor.py --delete