name: Cost Janitor

on:
  push:
    branches:
      - main

jobs:
  run-janitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install boto3

      # ✅ Start LocalStack manually
      - name: Start LocalStack
        run: |
          docker run -d -p 4566:4566 \
          -e SERVICES=s3,ec2 \
          -e AWS_DEFAULT_REGION=us-east-1 \
          -e DEBUG=1 \
          localstack/localstack

      # ✅ REAL WAIT (health check, not dumb sleep)
      - name: Wait for LocalStack
        run: |
          for i in {1..15}; do
            echo "Checking LocalStack health..."
            curl -s http://127.0.0.1:4566/health | grep "running" && break
            echo "Not ready yet, waiting..."
            sleep 5
          done
